# Generated by Django 3.2.4 on 2021-07-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Communities',
            new_name='Community',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Question_responses',
            new_name='Question_response',
        ),
    ]
