# Generated by Django 3.2.4 on 2021-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AddField(
            model_name='community',
            name='community_code',
            field=models.CharField(default='4C7B4A', max_length=6),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
