# Generated by Django 3.2.4 on 2021-07-22 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0003_auto_20210722_0452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_response',
            new_name='QuestionResponse',
        ),
    ]
