# Generated by Django 3.2.4 on 2021-07-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recall', '0005_auto_20210722_0634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityMembers',
            new_name='CommunityMember',
        ),
    ]
